### PR TITLE
Throw when try to set the root object

### PR DESCRIPTION
**Pull request by IvanGoncharov**
Before this changes:
```js
var obj = {};
pointer.set(obj, '', 'bla');
console.log(JSON.stringify(obj)); //{"undefined": "bla"}
```

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@manuelstofer @epoberezkin Can you please review this PR?

**Comment by epoberezkin** [comment]
looks good

**Comment by epoberezkin** [comment]
@IvanGoncharov Actually some note in docs would be helpful here too... I don't mind adding it or you can, please let me know.

**Comment by IvanGoncharov** [comment]
@epoberezkin Thanks, it would be great if you add it 👍

**Pull request merged**
