### PR TITLE
fix: 🐛 fix prototype pollution

### PR DESCRIPTION
**Pull request by AdamGold**
filter prototype, __proto__ and constructor

### CODE REVIEW

**Comment by manuelstofer** [comment]
Hi Adam, thank you for the pull request!

**Review by CryptoGGytrs52 — COMMENTED** [review]
Var

**Comment by SVilgelm** [comment]
@manuelstofer would you be able to release a new version, so we can get update our `package-log.json` files?

**Comment by SVilgelm** [comment]
> @manuelstofer would you be able to release a new version, so we can get update our `package-log.json` files?
> 
> thank you!

sorry, wrong ticket, I though that this one is already merged: https://github.com/manuelstofer/json-pointer/pull/36

**Review by RonSherfey — COMMENTED** [review]
Reviewed patch for vulnerabilities.

**Pull request merged**
